// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// frb_marker: #[frb(init)]
Future<void> initApp() => RustLib.instance.api.crateApiSimpleInitApp();

/// frb_marker: #[frb(sync)]
Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> decompress7Z({required String src, required String dest}) =>
    RustLib.instance.api.crateApiSimpleDecompress7Z(src: src, dest: dest);
